name: ssunet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip
  - pip:
    - numpy==1.26.4
    - h5py
    - pyyaml
    - tqdm
    - matplotlib
    - seaborn
    - pandas
    - lightning
    - pyiqa
    - pytest
    - ruff
    - tox
    - pre-commit
    - -e .
