name: ssunet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu124
    - torchvision --index-url https://download.pytorch.org/whl/cu124
    - torchaudio --index-url https://download.pytorch.org/whl/cu124
    - numpy==1.26.4
    - h5py
    - pyyaml
    - tqdm
    - matplotlib
    - seaborn
    - pandas
    - lightning
    - pyiqa
    - pytest
    - ruff
    - tox
    - pre-commit
    - -e .
