PATH:
  data_dir: "../../tempdata/Simulated_data"
  data_file: "RES_4341_p=0.00781_m=0.00776.tif"
  data_begin_slice: 0
  data_end_slice: 3600

  reference_dir: "../../tempdata/Simulated_data"
  reference_file: "RES_4341_p=0.00781_m=0.00776.tif"
  reference_begin_slice: 0
  reference_end_slice: 3600

  ground_truth_dir: "../../tempdata/Simulated_data"
  ground_truth_file: "ref.tif"
  ground_truth_begin_slice: 3601
  ground_truth_end_slice: 3856

DATA:
  xy_size: 128
  z_size: 32
  virtual_size: 600
  augments: False
  rotation: 0
  random_crop: True
  skip_frames: 1
  normalize_target: True
  note: "test"

SPLIT:
  method: "signal"
  min_p: 0.000001
  max_p: 0.999999
  p_list: Null
  normalize_target: True
  seed: Null

MODEL:
  channels: 1
  depth: 5
  start_filts: 32
  depth_scale: 2
  depth_scale_stop: 10
  z_conv_stage: 5
  group_norm: 8
  skip_depth: 0
  dropout_p: 0.0
  scale_factor: 10.0
  sin_encoding: False
  signal_levels: 10
  masked: True
  down_checkpointing: true
  up_checkpointing: False
  loss_function: "photon"
  up_mode: "pixelshuffle"
  merge_mode: "concat"
  down_mode: "maxpool"
  activation: "gelu"
  block_type: "tri"
  note: ""
  optimizer_config:
    name: "adamw" # "adam" | "sgd" | "adamw"
    lr: 0.0002
    mode: "min" # "min" | "max"
    factor: 0.5
    patience: 5

LOADER:
  batch_size: 15
  shuffle: False
  pin_memory: False
  drop_last: True
  num_workers: 6
  persistent_workers: True

TRAIN:
  default_root_dir: "../models"
  accelerator: "cuda"
  gradient_clip_val: 1
  precision: "32"
  max_epochs: 150
  device_numbers: 0

  callbacks_model_checkpoint: True
  mc_save_weights_only: True
  mc_mode: "min"
  mc_monitor: "val_loss"
  mc_save_top_k: 2

  callbacks_learning_rate_monitor: True
  lrm_logging_interval: "epoch"

  callbacks_early_stopping: False
  es_monitor: "val_loss"
  es_patience: 25

  callbacks_device_stats_monitor: False

  logger_name: "logs"
  profiler: "simple"
  limit_val_batches: 20
  log_every_n_steps: 20
  note: ""
  matmul_precision: "high"
